steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/fragrance-scout:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/fragrance-scout:latest'
      - '.'

  # Push the container image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/fragrance-scout:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/fragrance-scout:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update'
      - 'fragrance-scout'
      - '--image=gcr.io/$PROJECT_ID/fragrance-scout:$COMMIT_SHA'
      - '--region=us-west1'
      - '--platform=managed'

images:
  - 'gcr.io/$PROJECT_ID/fragrance-scout:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/fragrance-scout:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'
